package sg.edu.nus.iss.paf_day23.repository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import sg.edu.nus.iss.paf_day23.model.Customer;

@Repository
public class CustomerRepo {
    @Autowired
    JdbcTemplate jdbc;

    private final String findAllSql = "select id, first_name, last_name from customer";

    private final String findByIdSql = "select * from customer where id = ?";

    private final String insertSql = "insert into customer (first_name, last_name) values (?, ?)";

    private final String updateSql = "update customer set first_name =?, last_name = ? where id = ?";

    public List<Customer> getAllCustomers(){
        List<Customer> customerList = jdbc.query(findAllSql,BeanPropertyRowMapper.newInstance(Customer.class));

        return customerList;
    }

    public Customer getByIdCustomer(Integer id){
        Customer c = new Customer();
        c = jdbc.queryForObject(findByIdSql, BeanPropertyRowMapper.newInstance(Customer.class), id);
        
        return c;
    }

    public Integer createCustomer(Customer customer){
        jdbc.update(insertSql, customer.getFirstName(),customer.getLastName());

        //might return error since id should be auto generated by sql / jdbc and this is pojo
        return customer.getId();
    }

    public Integer updateCustomer (Customer customer){
        int iUpdated = 0;
        iUpdated = jdbc.update(updateSql, customer.getFirstName(),customer.getLastName(), customer.getId());
        return iUpdated;
    }

}
